name: getoutofthebox
description: "getoutofthebox project"

publish_to: "none"
# com.psychology.getoutofbox
# Store: C:\Users\nykolay\.android\debug.keystore
# Alias: AndroidDebugKey
# MD5: 1A:1B:7B:45:BB:8E:04:77:7E:34:CB:50:D4:D6:BA:EA
# SHA1: 30:21:88:87:8D:91:95:9E:E0:C7:63:57:F9:6F:6C:23:E1:28:C2:2E
# SHA-256: F9:10:30:E4:87:D0:3B:98:76:A9:12:83:92:92:18:10:E5:F7:9E:3F:4C:C5:9B:2A:BD:0C:A0:43:CD:B0:30:6A
# facebook
# ID: 628501293298970
 # Секрет: 5357105730c3547439c40811bf2cdc13


version: 0.1.9+9

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 # https://pub.dev/packages/cupertino_icons
  equatable: ^2.0.7 #https://pub.dev/packages/equatable
  flutter_screenutil: ^5.9.3 # https://pub.dev/packages/flutter_screenutil
  flutter_svg: ^2.0.16 # https://pub.dev/packages/flutter_svg
  flutter_rating_bar: ^4.0.1 # https://pub.dev/packages/flutter_rating_bar
  flutter_picker: ^2.1.0 # https://pub.dev/packages/flutter_picker
  dio: ^5.7.0 # https://pub.dev/packages/dio
  flutter_secure_storage: ^9.2.2 #https://pub.dev/packages/flutter_secure_storage
  get_it: ^8.0.3 # https://pub.dev/packages/get_it
  talker: ^4.6.0 # https://pub.dev/packages/talker
  get: ^4.6.6 # https://pub.dev/packages/get
  flutter_bloc: ^9.0.0 # https://pub.dev/packages/flutter_bloc
  shared_preferences: ^2.3.5 # https://pub.dev/packages/shared_preferences
  bloc: ^9.0.0 # https://pub.dev/packages/bloc
  url_launcher: ^6.3.1 # https://pub.dev/packages/url_launcher
  google_sign_in: ^6.2.2 # https://pub.dev/packages/google_sign_in
  firebase_auth: ^5.4.1 # https://pub.dev/packages/firebase_auth
  firebase_core: ^3.10.1 # https://pub.dev/packages/firebase_core
  flutter_facebook_auth: ^7.1.1 # https://pub.dev/packages/flutter_facebook_auth
  flutter_easylogger: ^2.3.3 # https://pub.dev/packages/flutter_easylogger
  gap: ^3.0.1 #https://pub.dev/packages/gap
  flutter_launcher_icons: ^0.14.3 #https://pub.dev/packages/flutter_launcher_icons
  cached_network_image: ^3.4.1 #https://pub.dev/packages/cached_network_image
  intl: ^0.19.0 #https://pub.dev/packages/intl

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true  
  ios: true
  remove_alpha_ios: true
  image_path: assets/logo.png
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/logo.png" 

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/main_page/
    - assets/img/
    - assets/svg/
    

  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/regular.otf
        - asset: assets/fonts/bold.otf
          weight: 700