// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzdkjLjmQpoDgyWkqfPrJuDQSZA9nPUuk',
    appId: '1:397695611758:android:30ece44df301c2859f477f',
    messagingSenderId: '397695611758',
    projectId: 'psychology-45c30',
    storageBucket: 'psychology-45c30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuhQMTD9Gc9JBTx6HFyAf5jp4xFR8KvfQ',
    appId: '1:397695611758:ios:fefd5b2fce4586bb9f477f',
    messagingSenderId: '397695611758',
    projectId: 'psychology-45c30',
    storageBucket: 'psychology-45c30.firebasestorage.app',
    androidClientId: '397695611758-4e5n708ljlskv9dqga53jgnnbidrhjcs.apps.googleusercontent.com',
    iosClientId: '397695611758-0qaa2neav8aj3d4ce5lngri839vvc3ml.apps.googleusercontent.com',
    iosBundleId: 'com.psychology.getoutofbox',
  );
}
